services:

  softcenter-app:
    container_name: softcenter-app
    build: .
    volumes:
      - ./softcenter-app:/var/www/html
    ports:
      - 9099:80
  
  mysql_db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: softcenter_app
    ports:
    - 3399:3306
  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 9098:80
    environment:
      - PMA_ARBITRARY=1